[package]
name = "ans"
version = "0.2.0"
authors = ["Arc <attobop@gmail.com>"]
edition = "2021"
description = "Asymmetric Numeral Systems: near-optimal entropy coding primitives."
license = "MIT OR Apache-2.0"
repository = "https://github.com/arclabs561/ans"
homepage = "https://github.com/arclabs561/ans"
documentation = "https://docs.rs/ans"
readme = "README.md"
keywords = ["ans", "entropy-coding", "compression"]
categories = ["compression", "algorithms"]

[workspace]

[features]
default = ["std"]
std = []

[dependencies]

[dev-dependencies]
proptest = "1.5"
fingerprints = "0.1"
